#!/bin/bash

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

cd "$(dirname "$0")/.." || exec echo "Failed to cd to parent directory!"

pwd

(
  cd "$(dirname "$0")/../../../.." || exec echo "Failed to cd!"

  pwd

  if [ -s "Gemfile" ]; then
      bundle check >/dev/null 2>&1 || {
        echo "==> Installing gem dependencies..."
        bundle install --quiet # --without production
      }
    fi
)

[ -s db/development.sqlite3 ] && [ -s db/test.sqlite3 ] || {
bundle exec rake db:create db:migrate
}
