#!/bin/bash

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e
error_report() {
  if [ "$1" != "0" ]; then
    echo "$0: Error $1 on line #$2" >&2
  fi
  return "$1"
}
trap 'error_report $? $LINENO' ERR

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> Setting up DB..."
# reset database to a fresh state.
bundle exec rake db:drop || echo Ignore error on db:drop
# Force it to recalculate db/schema from migrations rather than use db:reset
rm -f db/schema.rb
bundle exec rake db:create
bundle exec rake db:migrate db:seed db:test:prepare

echo "==> App is now ready to go!"
